### ISSUE TITLE
Add a "close" button 

### ISSUE THREAD

**Issue by herver** [pierr3/TrackAudio#10]
First of all, thanks for the wonderful ATC client :smile: 

I have a small improvement request: when using TrackAudio on Linux and a Window manager that doesn't decorate applications with the usual buttons, it's impossible to close TrackAudio properly, see screenshot: 

![image](https://github.com/pierr3/TrackAudio/assets/218323/2271039a-6fd1-43c3-b628-5e77148c2808)

It would be really nice to have an `X` button somewhere in a corner to close TrackAudio without having to `xkill` or pkill it :)

**Comment by pierr3** [comment]
ACK, will add
