### ISSUE TITLE
Some stations make the entire UI disappear

### ISSUE THREAD

**Issue by neilenns** [pierr3/TrackAudio#106]
To reproduce:

1. Connect
2. Add `KSJC_ATIS` or `KOAK_ATIS` as a station

Result: Entire UI goes blank
Expected result: Station added

![ksjc_bad_juju](https://github.com/pierr3/TrackAudio/assets/9524118/4ea82cd3-0496-46e8-87c4-6a338953ba0f)

This doesn't happen with other ATIS stations like `KPDX_ATIS`, `KSEA_ATIS`, etc.

ZSE best Z 😀

**Comment by pierr3** [comment]
Fixed in 21b2e2f1d2cec4e1e588718a28901b64ad64e0e4
