### ISSUE TITLE
Track audio sometimes not receiving one freq. but receiving others

### ISSUE THREAD

**Issue by Hypekingfish** [pierr3/TrackAudio#107]
Recieved audio from both PDX_TWR and SEA_CTR but when SEA_TWR was checked no audio came through

**Comment by Hypekingfish** [comment]
Audio is now skipping sometimes

**Comment by neilenns** [comment]
Here's a screenshot of this in action:

![image](https://github.com/pierr3/TrackAudio/assets/9524118/00de23b6-eef1-48c9-824d-2c86a50d691c)

I was transmitting on SEA_E_TWR and planes could hear me fine, but OP could not. Even refreshing the transceiver wouldn't fix it. OP reconnected as OBS for SEA_TWR and could hear me fine, just not when connected as OBS for SEA_CTR.

**Comment by pierr3** [comment]
Should be fixed in current beta
