### ISSUE TITLE
Not able to connect to ATC training session

### ISSUE THREAD

**Issue by Pirx-ThePilot** [pierr3/TrackAudio#112]
Hi,

First of all thank for great product & contribution for vATC community.
Recently I've start C1 training and when I connect as ex. EPWW_JT_CTR into EuroScope I am not able to connect with Track Audio.

ps. normally the callsign is EPWW_J_CTR, but for training session I need to add T.

Krzysztof

**Comment by pierr3** [comment]
Hi, can you please describe in much more detail what "not able to connect"
means? You cannot click the connect button? The frequency does not load?

Thanks

**Comment by Pirx-ThePilot** [comment]
It says "Station not found".

![obraz](https://github.com/pierr3/TrackAudio/assets/141395292/e2b65f99-c7a8-4e99-9b26-0290e45462be)
