### ISSUE TITLE
A Javascript error occured on the main process when opening trackaudio for the first time

### ISSUE THREAD

**Issue by i6iesma** [pierr3/TrackAudio#120]
Hi, today I tried to install trackaudio on a macbook Pro from 2015 with MacOS Monterey. When opening the app this error shows up. 
<img width="301" alt="Captura de Pantalla 2024-06-25 a las 13 16 51" src="https://github.com/pierr3/TrackAudio/assets/89868264/5d460127-8dd6-4089-a747-cce6a981743b">
<img width="277" alt="Captura de Pantalla 2024-06-25 a las 13 19 29" src="https://github.com/pierr3/TrackAudio/assets/89868264/cb2b55b8-e0a7-4d9f-9357-c600c31a8412">
I tried with previous releases but this starts showing on 1.1.0 and before the forced upgrade appears. 
Let me know if you need more information to try to debug this and thanks!

**Comment by neilenns** [comment]
Can you try uninstalling TrackAudio completely and then installing the latest release to see if that fixes it?

**Comment by pierr3** [comment]
If you’re on mac x64, the current build is broken - will push a new version
soon :)

**Comment by pierr3** [comment]
Fixed 1.2
