### ISSUE TITLE
Trackaudio timing out at unregular times

### ISSUE THREAD

**Issue by SpectreLoki** [pierr3/TrackAudio#125]
When I'm on HNL_02_CTR from time to time suddenly my connection seems to time out. I can't hear planes and neither can they hear me, the Tx lights up when I press my PTT but nothing gets transmitted and also the Rx light is not coming on at all when a plane sends a message.

Only solution for it right now is to disconnect and connect again.

**Comment by pierr3** [comment]
Does this occur regularly? This main have coincided with instability of AFV servers at the time

**Comment by SpectreLoki** [comment]
Can't really measure if it's regularly given that it happens without any warning and when there was no traffic on frequency and it happens then you don't even know until a pilot might open a chat and asks

**Comment by pierr3** [comment]
Should be fixed in current beta
