### ISSUE TITLE
Slurper parsing error tone

### ISSUE THREAD

**Issue by maxlk96** [pierr3/TrackAudio#126]
Hello, I am using mini mode and keep missing this error when it appears.

Would there be any way to have it show the error in a separate window bigger than the main window, or at least play some kind of warning tone? (or louder if it is already there, I've missed it every time)

Ideally if the connection to the slurper is just interrupted a short moment, could it not reconnect automatically?

![image](https://github.com/pierr3/TrackAudio/assets/25370081/17fb7310-23aa-4504-ba78-df9108b18c00)

**Comment by pierr3** [comment]
I verified that the tone does indeed not properly occur, I will fix it. Could you also share your trackaudio.log by any chance?

**Comment by pierr3** [comment]
Fix in current beta
