### ISSUE TITLE
Initial `npm install` fails on Windows

### ISSUE THREAD

**Issue by neilenns** [pierr3/TrackAudio#14]
To reproduce:

1. Clone the repo
2. Run `npm install` as listed in the README.md file for first step

Result:

```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path D:\git\TrackAudio\backend\trackaudio-afv-1.0.0.tgz
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'D:\git\TrackAudio\backend\trackaudio-afv-1.0.0.tgz'
```

Expected result:

No errors

**Comment by pierr3** [comment]
You first need to run npm run build-backend, then npm i.

Make sure you clone all submodules with git submodule update --init --recursive

**Comment by neilenns** [comment]
Ok, I'll give that a try. I'm going by the order in the readme, which says `npm install` is the first step:

```
npm install
git submodule update --init --recursive
npm run build-backend
npm run start
```

**Comment by pierr3** [comment]
Oops, need to change that

**Comment by neilenns** [comment]
Other things I've had to do so far:

1. `npm install -g cmake-js`
2. Add `Desktop development with C++` to my existing VS2022 install

Will keep adding to this as I find new things that need installing/documenting.

**Comment by neilenns** [comment]
Ok it built and ran! Amazing! I'll open a PR shortly with readme modifications.
