### ISSUE TITLE
Define Multiple PTT inputs

### ISSUE THREAD

**Issue by Terminal-Rat** [pierr3/TrackAudio#142]
I utilize two different devices for PTT based on what type of position I'm controlling and what else I have going on, a foot switch and a handheld PTT button. Currently I have to use external software to map both devices to the same keyboard keypress so I can use them both. CRC's AFV implementation allows 2 PTT inputs to be defined which eliminates the need for the extra program running. Adding this feature to TrackAudio would be useful.

**Comment by neilenns** [comment]
@pierr3 Want me to open that pull request? 😅

**Comment by TryFanGamer** [comment]
I do too

**Comment by pierr3** [comment]
Fine, we'll add a second one ;P

**Comment by neilenns** [comment]
@Terminal-Rat @TryFanGamer This is now available in [beta 2](https://github.com/pierr3/TrackAudio/releases/tag/1.3.0-beta.2).
