### ISSUE TITLE
Settings will crash TA

### ISSUE THREAD

**Issue by kusterjs** [pierr3/TrackAudio#145]
With the version 1.3.0 on Windows, Track Audio crashes on my computer without any notification or message when hitting the Settings button. Had to delete the ``%appdata%/TrackAudio`` folder. No entries were made in the log file.

I previously had installed 1.2.0 (my first installation on this machine).

**Comment by neilenns** [comment]
Do you still have the `config.json` file from your `%appdata%/TrackAudio` folder? If so, can you attach it here? Thanks!

**Comment by neilenns** [comment]
(This is probably already fixed with #144)

**Comment by kusterjs** [comment]
[config.json](https://github.com/user-attachments/files/16397359/config.json)
In case you still want to have a look or test something.

**Comment by pierr3** [comment]
This should be a known issue that we will fix in the next beta! We changed
the way the audio handling works, Niels’s PR should fix it

**Comment by kusterjs** [comment]
Ok, thanks.

**Comment by Erdemes** [comment]
Issue still persists with 1.3.0 beta1.
