### ISSUE TITLE
Small window size hides buttons and content

### ISSUE THREAD

**Issue by kusterjs** [pierr3/TrackAudio#146]
Upon installing the 1.3.0 beta, my windows default size was quite small, resulting in no buttons and neither the right column of the main window being displayed. While the resizing seems to work as designed, wouldn't it make sense to require a minimum size for the large window mode, so that no parts of the application are hidden?
From a few tests, I seems like the mini mode is already a defined resizing, which results in hiding parts of the application. Since the button to go back to the large window mode is hidden by default, my initial user reaction was just to resize the window manually, which lead to the same situation where not all content was shown.

**Comment by neilenns** [comment]
Have you ever had TrackAudio installed before? Or was the beta your first install?

**Comment by kusterjs** [comment]
I had 1.2.0 installed before.

**Comment by neilenns** [comment]
Ok. Just so I understand, on first launch it was narrower than you expected (which hid the sidebar), but once you resized it bigger it's properly remembering that size across app launches?

**Comment by kusterjs** [comment]
No, it doesn't. It's always launched in smaller size.

**Comment by neilenns** [comment]
> No, it doesn't. It's always launched in smaller size.

Hmmmm. What platform are you on?

**Comment by kusterjs** [comment]
Windows 11. In fact the window get's smaller with every time. So if I don't resize, it will be even smaller the next time. Looks like a wrong value is saved for the window size.

https://github.com/user-attachments/assets/17959dd2-ed14-4a8d-8f43-bb5c4c0b3ed8

**Comment by neilenns** [comment]
Thanks for the video! A few follow-ups:

1. Do you have multiple monitors?
2. Is this on your primary or your secondary monitor?
3. Is the monitor 4k?

**Comment by kusterjs** [comment]
Yes, multiple monitors. This is my secondary, which is not a 4K. The primary though is one.

**Comment by neilenns** [comment]
> Yes, multiple monitors. This is my secondary, which is not a 4K. The primary though is one.

Ok I was afraid of that.

Does it work correctly if you do this on your primary monitor?

**Comment by kusterjs** [comment]
Yes, there it seems to work.

Also just noticed that the mini window version will keep its old place (if I don't specifically move it). But I guess this is a desired behaviour?

**Comment by neilenns** [comment]
The remembering position is by design, implemented here: https://github.com/pierr3/TrackAudio/issues/146. It matches the vatis behaviour and means you don't have to re-position the mini-mode to your favourite place every time you run TrackAudio.

Your issue is, unfortunately, a bug. You can see my mention of it here: https://github.com/pierr3/TrackAudio/pull/103.

**Comment by neilenns** [comment]
Digging into this a bit, it appears to be an underlying issue with Electron and multiple monitors that have different scaling percentages. I've found at least two open issues in their github with similar symptoms, neither of which have any response from an Electron developer :(

Will poke around and see if I can find a workaround.

**Comment by pierr3** [comment]
Please try beta 2 to see if Neil's fix worked

**Comment by pierr3** [comment]
Closing as stale
