### ISSUE TITLE
Station not found with SUP connection

### ISSUE THREAD

**Issue by vFlyingCowboy** [pierr3/TrackAudio#149]
When I connect to the network with a supervisor connection, the pop up for station not found shows up. Is it possible that if you create a SUP connection, that gets omitted?

**Comment by neilenns** [comment]
What version of TrackAudio are you using? Sounds an issue that was fixed in beta 1.3.0-beta.1.

**Comment by pierr3** [comment]
It's also expected behaviour, since SUP is considered an ATC, it will try to fetch the station in database. No harms in this case :)
