### ISSUE TITLE
`StationRxBegin` is sent twice on every RxBegin

### ISSUE THREAD

**Issue by neilenns** [pierr3/TrackAudio#152]
(Logging this against TrackAudio since I can't open issues against afv-native)

Every time RX happens TrackAudio receives the `StationRxBegin` message twice. I noticed this in my streamdeck plugin because I was re-rendering the buttons twice on every RX and thought it was an SDK issue. However, I added a log message to TrackAudio and it's also getting sent `StationRxBegin` twice.

Looks like an afv-native issue?

**Comment by pierr3** [comment]
afv-native issue, might be fixed in next release.
