### ISSUE TITLE
TrackAudio not starting

### ISSUE THREAD

**Issue by L1011H** [pierr3/TrackAudio#153]
Hello,

Ubuntu 22.04(Cinnamon):
Snap: Installed with snap install <packagename>--dangerous, shows on the menu as expected. Exits with no window shown on the screen, no output on terminal and immediately bash command prompt.

Appimage : outputs core dump message on the terminal & exits.

Windows 7 under KVM (unsupported?): Does not run with "DiscardVirtualMemory Entry Point Missing From Kernel32.dll" message.

**Comment by pierr3** [comment]
Can you share the core dump from the app image run?

**Comment by L1011H** [comment]
I have re-downloaded the appimage and I can't reproduce the problem this time. I suspect file/directory permissions were the culprit the first time around.

**Comment by neilenns** [comment]
> I'm seeing the same behaviour on Windows 10 using Track Audio 1.3.0-beta.1-x64

Odd, I've had no issues running TrackAudio on Windows since the beta came out. Can you try uninstalling it @chssn and then install a fresh copy to see if that resolves the problem?

**Comment by pierr3** [comment]
Can you both try to delete your config files and reset your devices?

**Comment by neilenns** [comment]
This is probably the same config issue that's addressed with #144.
