### ISSUE TITLE
Unable to reconnect after AFV timeout

### ISSUE THREAD

**Issue by kusterjs** [pierr3/TrackAudio#155]
In todays session, I suddenly received a popup that the connection to the AFV slurper was terminated. Fortunately, there was a nice warning sound making me aware of this immediately.
However, the problem thereafter was that I found no way to reconnect TrackAudio again other than a complete restart of the application. The Connect button would stay inactive despite the FSD connection was running fine.
Is this supposed to be that way? If not, what logs should I provide for further investigation?

**Comment by neilenns** [comment]
@kusterjs What version of TrackAudio were you running?

**Comment by kusterjs** [comment]
1.3.0-beta.1

**Comment by neilenns** [comment]
> 1.3.0-beta.1

Odd. Haven't seen that before on my Windows install. If it happens again can you upload the logs, although I doubt it will shed much light. The logs are in `%localappdata%\TrackAudio\trackaudio.log`.

**Comment by kusterjs** [comment]
[trackaudio_2024-08-13.log](https://github.com/user-attachments/files/16619556/trackaudio_2024-08-13.log)
Here is the extract from this session. Disconnect happened around 21:49. What got my attention are the few entries around that time with a different timestamp, which is when I started the application first. I didn't change anything in the sequence of the log.

**Comment by neilenns** [comment]
Thanks. I can definitely see where the slurper error happened and it failed the one attempt to reconnect:

```
[2024-08-13 21:43:13.220] [trackaudio_logger] [error] Slurper returned an HTTP error 500. Giving it one more try
[2024-08-13 21:49:13.015] [trackaudio_logger] [error] Slurper returned an HTTP error 500
```

From my reading of the code I *think* this should still keep re-checking for a valid slurper connection and then light the button up, but it's a little tough to follow. @pierr3 will need to take a peek once he has a chance.

**Comment by pierr3** [comment]
It might just be a timing thing, I'll double check but yes the slurper connection is supposed to keep re-trying

**Comment by pierr3** [comment]
Closing as stale, should be fixed, reopen if needed
