### ISSUE TITLE
Wrong frequency for CYZX_TWR

### ISSUE THREAD

**Issue by reiji69** [pierr3/TrackAudio#159]
![image](https://github.com/user-attachments/assets/22c8df1e-0675-4507-ba29-2b4311e9f2cc)
![image](https://github.com/user-attachments/assets/528801c3-d320-430f-9e19-96219ec47a41)
CYZX_TWR frequency set to 118.4 instead of 119.5

**Comment by pierr3** [comment]
You need to speak to your division for this, it's them that set frequencies.
