### ISSUE TITLE
Beta 1.3 - Crash when hitting settings

### ISSUE THREAD

**Issue by gerardojro** [pierr3/TrackAudio#162]
Just as the title suggests, downloaded and installed the 1.3 beta and when I hit settings I get a CTD with no warning whatsoever.

**Comment by neilenns** [comment]
> Just as the title suggests, downloaded and installed the 1.3 beta and when I hit settings I get a CTD with no warning whatsoever.

You need to delete your config file and it'll be fine. Are you on Windows? If so, the file is located at `%appdata%\TrackAudio\config.json`. Just delete the file then run TrackAudio again and re-configure your audio settings.

**Comment by pierr3** [comment]
Fixed in beta 2
