### ISSUE TITLE
1.3.0-beta.1 - Speaker function not working

### ISSUE THREAD

**Issue by DotWallop** [pierr3/TrackAudio#163]
SPK button is not working. Attempted to run as admin, choosing different outputs, etc. Is just quiet, can instantly hear again when depressing it.

1.3.0-beta.1

**Comment by neilenns** [comment]
Try deleting your config.json file then reconfiguring all your audio settings again. If you are on windows the file is located at `%appdata%\trackaudio\config.json`.

**Comment by pierr3** [comment]
Should be fixed with forced settings reset
