### ISSUE TITLE
1.3.0 beta1 not transmitting or recceivng

### ISSUE THREAD

**Issue by sk0941** [pierr3/TrackAudio#164]
I tried the new beta, but I can't transmit nor hear anyone. But on my end it looks like I'm transmitting but nothing is coming through

**Comment by neilenns** [comment]
@sk0941 Did you reset your audio settings?

**Comment by sk0941** [comment]
Yea, I tried to delete the settings.json file, but that made no difference. I was trying out the stream deck plugin if that makes a difference.

**Comment by neilenns** [comment]
Hmmm interesting. What platform are you on? Can you post a screenshot of your main window showing the station you added and what's enabled for that station?

**Comment by sk0941** [comment]
I went back to 1.2.0 for now. I had added CZVR_CTR with TX and RX enabled, I can't grab a screenshot right now as I'm currently controlling.

**Comment by neilenns** [comment]
> I went back to 1.2.0 for now. I had added CZVR_CTR with TX and RX enabled, I can't grab a screenshot right now as I'm currently controlling.

You should have "XCA" enabled for your primary position, that might have been the issue? Let me know next time you give it a try.

Also, send some planes south, we are bored AF right now at SEA!

**Comment by sk0941** [comment]
Will try haha, you've got WAT soon

**Comment by neilenns** [comment]
> Will try haha, you've got WAT soon

I will be closed *well* before that 😆

**Comment by sk0941** [comment]
![bild](https://github.com/user-attachments/assets/8c12491c-bd2d-430d-915d-bd5c50357d3e)

This is what it look slike for me, if I use my PTT it looks like I'm transmitting but nothing goes through and I can't hear anyone either. Like not even static is coming through when I hit the PTT

**Comment by sk0941** [comment]
huh, well, seems like all I had to do was to select WASAPI under audio API

**Comment by neilenns** [comment]
Glad you got it working! Let me know how the streamdeck buttons work out.

**Comment by pierr3** [comment]
Should be fixed in next beta
