### ISSUE TITLE
Connect Button breaks, if network is not available

### ISSUE THREAD

**Issue by GeheimagentNr1** [pierr3/TrackAudio#165]
Version: 1.3.0-beta1

If the Vatsim network is not available, for example if the servers are down, the connect button, stays disabled and has the text "Connecting...".

![image](https://github.com/user-attachments/assets/2ab8b6da-99b7-4171-8fc3-4774404a6de1)

**Comment by pierr3** [comment]
Duplicate of #155 - please track the issue there
