### ISSUE TITLE
PTT Key pressed

### ISSUE THREAD

**Issue by bostjanlaba** [pierr3/TrackAudio#167]
While 1.3.0 was ok, with beta 2 something is pushing my PTT (left ctrl). When I try to re-set ptt, it starts picking up num-lock. When I try to set ptt with AudioForVatsim, no such thing is happening. So I guess TrackAudio is picking up num-lock or ctrl key in my case whereas AFV does not.

**Comment by neilenns** [comment]
Can you post a screenshot of your settings dialog?

**Comment by neilenns** [comment]
Also what platform are you on?

**Comment by bostjanlaba** [comment]
![image](https://github.com/user-attachments/assets/d4485df7-9e37-405a-abc1-16e9fc5a0d1f)

**Comment by neilenns** [comment]
Can you try closing TrackAudio? Then run it again and try to configure the Ptt 1 key to be what you want.

**Comment by bostjanlaba** [comment]
Tried. I had to completely logout of Windows, then relogin but when I re-started TrackAudio. Seemed ok for short period of time, then I started opening Euroscope, vPilot, vAtis, MSFS etc and same issue. I could not isolate which app would make problems but both problems reappeared (pressed ctrl and num-lock in set-ptt/settings). None of this - at the same time - was a problem in AFV, if it helps.

**Comment by pierr3** [comment]
This sometimes happens with physical external devices: Joysticks, PTT pedals, extra keyboard, etc. Disconnect any unused devices from your machine, restart TrackAudio and set your Ptt. TrackAudio's input handling is quite unfiltered and it will pick up pretty much anything spamming an input

**Comment by bostjanlaba** [comment]
I know about that. But in this case no joystick, not pedals, nothing. I will retry 1.3.0 (no beta) to avoid PTT key locking and unwanter transmission and report back. However, any chance TA would behave like AFV which has no such issues with PTT? Different filtering of keys?

**Comment by neilenns** [comment]
> I know about that. But in this case no joystick, not pedals, nothing. I will retry 1.3.0 (no beta) to avoid PTT key locking and unwanter transmission and report back. However, any chance TA would behave like AFV which has no such issues with PTT? Different filtering of keys?

Can you try 1.3.0-beta.1? https://github.com/pierr3/TrackAudio/releases/tag/1.3.0-beta.1

**Comment by bostjanlaba** [comment]
1.3.0. beta 1 seems to be ok. Does not have issues in the settings for PTT and it does not auto-press TX when working

**Comment by neilenns** [comment]
Hmmmm. Now that it's worked with Beta 1, can you try going back to Beta 2 and see what happens?

**Comment by thomasljung** [comment]
It is the same in Beta3

**Comment by thomasljung** [comment]
Had to edit %localappdata%\TrackAudio

**Comment by neilenns** [comment]
> Had to edit %localappdata%\TrackAudio

Once you did does the key get detected properly when you try and PTT on network?

**Comment by thomasljung** [comment]
Yes, they did.

Best Regards
Thomas Ljung

---------------------------------
Ö. Stenby, Rotenberg 1
610 31  Vikbolandet

Tfn     070-620 62 10
E-post ***@***.***
---------------------------------


Den ons 30 okt. 2024 kl 23:05 skrev Neil Enns ***@***.***>:

**Comment by pierr3** [comment]
Tracking this in #211
