### ISSUE TITLE
[Enhancement] Last RX callsign(s) with multiple station talking at the same time

### ISSUE THREAD

**Issue by GeheimagentNr1** [pierr3/TrackAudio#169]
If 2 or more pilots are talking at the same time, only one callsign is shown in the "Last RX" list.
It would be nice, if the callsign of all talking pilots are shown.

**Comment by neilenns** [comment]
Ooooh a chance for me to plug the [StreamDeck actions](https://github.com/neilenns/streamdeck-trackaudio/) 😂 If you have a StreamDeck you can show up to four last receive callsigns on a button.

**Comment by pierr3** [comment]
This won't be changed in the UI for now (it's more complex than it looks), use the RDF plugin or the stream deck plugin
