### ISSUE TITLE
Connect Option Greyed Out

### ISSUE THREAD

**Issue by hughjersey** [pierr3/TrackAudio#170]
Hey there,

Forgive me @pierr3 as this might be a silly question to ask and me missing the obvious. I have started the client up, have populated the settings pane, yet cannot trigger a connection.

I could not find guidance on GitHub to connect, and tried trawling the internet. I have posted for support on Vatsim Discord and thought an issue here might be the best bet.

I'm using it on Debian 12 installed via the package provided. 

Again, apologies if this is user error. Thought it was worth checking. The Vatsim ID is a placeholder, not my real one, but provides the same outcome of a greyed out connect box.

![image](https://github.com/user-attachments/assets/f4a4b63e-8266-45bd-8273-b61b6a29c488)

![image](https://github.com/user-attachments/assets/542534f7-5bc3-47f1-a28e-7f9288325de4)

Thanks for any help,

Hugh

**Comment by neilenns** [comment]
What version of TrackAudio are you running?

**Comment by hughjersey** [comment]
> What version of TrackAudio are you running?

Hey @neilenns. Dear oh dear, not sure how I managed to omit that! 1.3.0-beta.2.

**Comment by neilenns** [comment]
> And to add @neilenns, I don't have any other clients with connections to Vatsim open. I have in my head that this is something I can use standalone for audio. I hope that's correct, otherwise may be a simple fix..

You need to have a controlling client open and a connection there active, e.g. in CRC or EuroScope.

**Comment by hughjersey** [comment]
Thanks @neilenns, the Vatsim team also informed me of that, and with EuroScope connected, things look good!

I am suffering from that same RX crash problem in the other issue now, but will check that thread out for that. 

The Vatsim team acknowledged that they don't actually have mention on their FAQ of needing a client connected to be able to use audio clients, and plan to add a notice. That's why I wasn't aware. It might be worth an add to your own docs to stop other people like me raising issues without knowing, or a warning within the software.

Either way, my issue is solved and I really appreciate the help and time you guys have put into the client. Thanks again.
