### ISSUE TITLE
Numbered positions (_1_, _W1_) not working

### ISSUE THREAD

**Issue by Chopan22** [pierr3/TrackAudio#172]
When connecting to a position that has another controller connected, the callsign gets a number (JFK_1_TWR), when this happens I can't set TX on the frequency (seems like it detects it as an observer).

**Comment by neilenns** [comment]
@Chopan22 What version of TrackAudio are you running

**Comment by Chopan22** [comment]
Damn I knew there was something I was probably missing. I'm using the 1.2.0 I'll update and see how it goes.

**Comment by Chopan22** [comment]
Ok so I tested it on the newest release and it doesn't work. It says "[0038Z] Station not found".

**Comment by neilenns** [comment]
@pierr3 Will need to comment. We've seen this before and I think it has to do with how your FE configured things.

**Comment by pierr3** [comment]
That's normal, those callsigns are not "normal" relief callsigns, as some vACCs do name sub sectors as _1_ _2_ _3_ etc. A supported relief callsign is one that uses multiple "_" like JFK__TWR

This is working as intended, you just need to manually input the callsign of the position.
