### ISSUE TITLE
Add "Guard" and "advisory/UNICOM" as options

### ISSUE THREAD

**Issue by DotWallop** [pierr3/TrackAudio#175]
Now that VATSIM has opened for usage of the international emergency frequency / "Guard", it would be a good option to have in the software. I can add it as a manual frequency, but then I cannot add it to my Streamdeck via plugin, as it requires a position name (perhaps with a visual queue differentiating it from other frequencies? Red-ish hue etc.)

Same thing could be added for UNICOM / Advisory. :)

**Comment by pierr3** [comment]
Would be good but the caveat is that it would only your visibility point as architecture, as right now transceivers are tied to a position callsign. I think we can add that however.

**Comment by pierr3** [comment]
This is on feature roadmap and being worked on

**Comment by pierr3** [comment]
Implemented
