### ISSUE TITLE
WinWing Orion2 HOTAS PTT select

### ISSUE THREAD

**Issue by skyelaird** [pierr3/TrackAudio#176]
TrackAudio autoselects my HOTAS (button 3?) as PTT 1/2. It refuses to scan inputs to change the selection.

I do want my PTT to be on that device but need to be able to select it. Would also want to be able to select a keyboard PTT while the HOTAS is connected.

**Comment by neilenns** [comment]
Does your HOTAS continually send a key down event for that button like the Honeycomb devices do?

If you disconnect the HOTAS are you able to set your PTT1 to the keyboard button you want?

**Comment by pierr3** [comment]
Tracking this in #211
