### ISSUE TITLE
Unknown PTT Button

### ISSUE THREAD

**Issue by YEET2395** [pierr3/TrackAudio#178]
Everytime I want to bind PTT to my Thrustmaster TCA, there is always this F22 key (PTTKey=73) that inputs and sets as PTT button.
However, when I disconnected all input devices except for keyboard and my mouse, this still occurs.

https://github.com/user-attachments/assets/7feb39e1-e17d-44df-a685-59a569f68ad2

**Comment by pierr3** [comment]
There is something on your system pressing that key, it's not track audio related per say, you will need to do a bit more digging on your side and see if you have any programmes running that may be causing this

**Comment by YEET2395** [comment]
> There is something on your system pressing that key, it's not track audio related per say, you will need to do a bit more digging on your side and see if you have any programmes running that may be causing this

I will try to find it, however, vpilot or AFV does not have this problem on my side

**Comment by pierr3** [comment]
They use a different way to detect keys, so that is to be expected.

**Comment by YEET2395** [comment]
> They use a different way to detect keys, so that is to be expected.

Ah I see, I will try to restart my computer and see if it help

**Comment by YEET2395** [comment]
> They use a different way to detect keys, so that is to be expected.

I don't think I can find the issue for this, is there a way to manually (not using key detection) select the PTT?

**Comment by neilenns** [comment]
> > They use a different way to detect keys, so that is to be expected.
> 
> I don't think I can find the issue for this, is there a way (or possibly add a function?) to manually (not using key detection) select the PTT?

You can try manually setting it in the settings.ini file if you know the key code for it. The file is located in `%localappdata%\TrackAudio` on Windows.

**Comment by YEET2395** [comment]
> > > They use a different way to detect keys, so that is to be expected.
> > 
> > 
> > I don't think I can find the issue for this, is there a way (or possibly add a function?) to manually (not using key detection) select the PTT?
> 
> You can try manually setting it in the settings.ini file if you know the key code for it. The file is located in `%localappdata%\TrackAudio` on Windows.

Thanks! I would try to find the key code for my TCA

**Comment by neilenns** [comment]
If it is a joystick you'll need both the button ID and the joystick ID.

**Comment by pierr3** [comment]
Tracking this in #211
