### ISSUE TITLE
Disconnect warning sound missing with 1.3.0b2

### ISSUE THREAD

**Issue by capzDE** [pierr3/TrackAudio#183]
The warning sound was working with 1.3.0b1, but after recently updating to 1.3.0b2, any warning sounds appear to be missing.

**Comment by neilenns** [comment]
What platform are you on? I was just using b2 on Windows and closed CRC without disconnecting TrackAudio and got the amazingly annoying "beep beep beep beep beep".

**Comment by capzDE** [comment]
> What platform are you on?
Win10 and ES 3.2.9

**Comment by pierr3** [comment]
Can you try beta 3?

**Comment by capzDE** [comment]
Have been using Beta 3 for a while now, the issue persists in that version, unfortunately.

**Comment by pierr3** [comment]
I've had the error sound play correctly in beta 4, please report if it works. Also keep in mind that the error sound will be played on your default system device (this is something we're working on but not changeable so far)

**Comment by capzDE** [comment]
It didn't play for me in Beta 4, so I guess it might be an issue on my end. I will further investigate this on my end, but closing the issue here.
