### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by SnivyCode** [pierr3/TrackAudio#190]
Hello, I'm trying to install TrackAudio but my anti virus keeps deleting it. Tried to disable the anti virus but still unable to install the program.
Anybody has my same issue?
I'm currently on Windows.

**Comment by pierr3** [comment]
This is going to be your anti-virus for sure, check that you do not have a secondary anti virus, or that your anti virus actually disables. The reason as to why it detects it is that some anti virus do not like the code that registers a push to talk button globally. This is not something that we can fix on our side.
