### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by Rube-B** [pierr3/TrackAudio#192]
I get this error over and over when installing and launching. Tried reinstalling, tried another version, tried updating java/node, tried running as administartor.
Nothing works.

![image](https://github.com/user-attachments/assets/e2f227fa-19cc-4f60-9bed-9508268461d9)

**Comment by GeorgeBarlow** [comment]
Trying to do a clean install again and ensure the directories below are empty before re-installing. Something may have not been copied across properly.

- `%appdata%/TrackAudio`
- `%localappdata%/Programs/trackaudio`

Report back your findings :)

**Comment by minsulander** [comment]
Same issue here on a fresh (as in nothing installed except drivers and EuroScope) Windows 10 computer, TrackAudio 1.3.0 beta 3.
`%appdata%/TrackAudio` contains one file, `Local State`.
`%localappdata%/Programs/trackaudio` contains the Electron-typical ridiculous amount of DLLs etc.

**Comment by GeorgeBarlow** [comment]
> Same issue here on a fresh (as in nothing installed except drivers and EuroScope) Windows 10 computer, TrackAudio 1.3.0 beta 3. `%appdata%/TrackAudio` contains one file, `Local State`. `%localappdata%/Programs/trackaudio` contains the Electron-typical ridiculous amount of DLLs etc.

Hmm, yeh it sounds like it can't find it or maybe can't load it?

Let's first of all just make sure you have the required file inside your `%localappdata%`, could you please navigate to:
`%localappdata%\Programs\trackaudio\resources\app.asar.unpacked\node_modules\trackaudio-afv\build\Release`

You should have a file called `trackaudio-afv.node` in this folder (I believe 25 files in total), could you let me know what you find :)

**Comment by pierr3** [comment]
Thank you for finding this out, we were not aware (as we mostly dev on mac) - I'll add it to the release notes and to the installer a bit later. Can everyone who has had this problem confirms that this fixes it?

**Comment by pierr3** [comment]
The error might have been that TrackAudio on windows is compiled on an old windows toolset, which is not shipped with modern versions of Windows. I've just bumped that so it might solve that issue out of the box

**Comment by pierr3** [comment]
@neilenns can you try and build the installer on latest? It includes vcredist installation

**Comment by neilenns** [comment]
@pierr3 Confirmed it fired off the vcredist installer.

![image](https://github.com/user-attachments/assets/217e06db-7af8-4fbd-a472-dcdeb49f9258)
