### ISSUE TITLE
GUARD and UNICOM should sort to bottom of mini-mode list

### ISSUE THREAD

**Issue by neilenns** [pierr3/TrackAudio#198]
![image](https://github.com/user-attachments/assets/f20a6975-6e1e-43cd-955b-8ff11198bdec)

Right now they just get inserted alphabetically, which means GUARD is in an odd spot and breaks up the list of local frequencies you care about. I polled exactly one other controller in my ARTCC and he agreed GUARD and UNICOM should always be at the end.

**Comment by neilenns** [comment]
Change would go in RadioHelper.ts that does the sorting.

**Comment by neilenns** [comment]
I have this coded up, just have to move it to be off the main branch.

**Comment by GeorgeBarlow** [comment]
> I have this coded up, just have to move it to be based on the main branch instead of new UI.

Yep this sounds good, we can review it after that PR has been merged, otherwise open a draft PR and just note that it depends on the other PR.

**Comment by neilenns** [comment]
It doesn't depend on it, I just accidentally created my branch off the ui branch because that's what I had pulled. Oops :D
