### ISSUE TITLE
Add a mini-mode

### ISSUE THREAD

**Issue by neilenns** [pierr3/TrackAudio#2]
Since you said it's all new UI, I'll make a request for all new features :D

I would love to have a mini mode that shows the last 2 (3? 5?) received callsigns and station and nothing else in a little list that I could run as an always on top window.

Realistic? No. But extremely helpful when listening to other frequencies while controlling or dealing with new pilots stepping on each other.

**Comment by pierr3** [comment]
Yes, will be much easier to do now! If you have tried, you'll see that the UI is already responsive and removes elements as the window gets smaller. This will be done, looking for opinion as to what to show: only the last few callsigns or anything else?

**Comment by neilenns** [comment]
Responsive UI is 🥰

Honestly all I want is a list that looks something like this:

* PDX_GND: SWA1243
* PDX_TWR: SWA2234

And have the list update to just show the last _n_ calls and the station they came in on

**Comment by pierr3** [comment]
<img width="202" alt="Screenshot 2024-04-27 at 17 09 34" src="https://github.com/pierr3/TrackAudio/assets/1833515/9fd5da17-311e-4cf0-bad4-e63f187c2316">
 :)

**Comment by neilenns** [comment]
> <img width="202" alt="Screenshot 2024-04-27 at 17 09 34" src="https://github.com/pierr3/TrackAudio/assets/1833515/9fd5da17-311e-4cf0-bad4-e63f187c2316">
>  :)

😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍

**Comment by pierr3** [comment]
Now available

**Comment by neilenns** [comment]
Woo! I'll give it a try tomorrow

**Comment by neilenns** [comment]
It's beautiful.

![image](https://github.com/pierr3/TrackAudio/assets/9524118/0b08776a-87ad-4e01-bcc4-d5178ec7791f)

I've combined it with the Windows PowerToys always on top command to make it float above all my other windows.

**Comment by pierr3** [comment]
Fantastic - you can also use the always on top option in the settings !

**Comment by neilenns** [comment]
I'm really glad I didn't open a feature request for that because I was going to eventually 😅
