### ISSUE TITLE
Mini-mode is blank until something is received on frequency

### ISSUE THREAD

**Issue by neilenns** [pierr3/TrackAudio#20]
To reproduce:

1. Connect, and "rx" a couple of different frequencies
2. Scale the window small to get mini-mode

Result: An empty screen
Expected result: The list of "rx" stations and something like "None" for the last received callsign

This is another one I'm happy to do the PR for if you like, looks like it can be done in the `setRx()` method and just default the `lastReceivedCallsign` and `lastReceivedCallsignHistory` to `"None"` and `["None"]` respectively when `value` is true.

**Comment by pierr3** [comment]
This is expected behaviour, if you want the radios to show this can be
changed in the component itself.

**Comment by neilenns** [comment]
Oh, right. Of course 🤦‍♂️just remove the filter from the component and conditionally render "none"
