### ISSUE TITLE
PTT not registering intermittently

### ISSUE THREAD

**Issue by Fechulo** [pierr3/TrackAudio#200]
Ever since I've updated to beta 3, I've had issues where TrackAudio stops registering my PTT every few minutes. It fixes itself after 30s or so but disconnecting and reconnecting fixes it as well. I use Right CTRL as my PTT but I encountered it with other keys and joystick buttons as well.

**Comment by neilenns** [comment]
What platform are you on?

**Comment by Fechulo** [comment]
Windows 10

**Comment by GeorgeBarlow** [comment]
There's a plan to overhaul the PTT system I believe, so hopefully this will be fixed soon.

**Comment by pierr3** [comment]
Tracking this in #211
