### ISSUE TITLE
From 1.3.0 crash when select a station automatically added or via station name [Linux / avf-native]

### ISSUE THREAD

**Issue by Ades128** [pierr3/TrackAudio#202]
On 1.3.0 b4
During investigations on [issue#157](https://github.com/pierr3/TrackAudio/issues/157) I found that in adding manual frequency it works.

Currently using:
6.11.6-arch1-1
pipewire-pulse 1:1.2.6-1
alsa-utils 1.2.12-1
gnome 47.0.1
xorg-server 21.1.14-1
libpulse 17.0-3

May be issue#157 was resolved with last updates ?

I found in backend/extern/afv-native/src/core/atcClient.cpp
line 499:
``` 
ClientEventCallback.invokeAll(ClientEventType::StationTransceiversUpdated,
                                  (void *) stationName.c_str(), nullptr); 
```

With LOG point investigations I found that stationName.c_str()  returns a  const char*  instead  void* 

I didn't make further investigations to know why, specially on my system, but here a workaround:

``` 
std::string stationNameCopy = stationName;
      ClientEventCallback.invokeAll(ClientEventType::StationTransceiversUpdated, (void*)&stationNameCopy, nullptr); ```

hope it helps

**Comment by pierr3** [comment]
I've received another report of the same.

Yes, stationName.c_str(), returns a const char*, and it's casted to void * (which prefixes it). Your workaround is a bit funky but I know how to fix this and will do!

**Comment by pierr3** [comment]
Give it a try on the current build (will be in next beta), should be fixed
