### ISSUE TITLE
`package-lock.json` changes on every backend build, driving every developer crazy

### ISSUE THREAD

**Issue by neilenns** [pierr3/TrackAudio#204]
To reproduce:

1. Run `npm run build:backend`
2. Run `npm run dev`
3. Enjoy coding/testing stuff
4. Let some time pass, let Pierre or Geroge check some cool new stuff into main
5. Run `git merge upstream/main`

Result: error: Your local changes to the following files would be overwritten by checkout: package-lock.json
Expected result: No merge conflict in package-lock.json

We've all been here and it SUCKS. It happens because every time the backend is built it updates `package-lock.json` with a hash for the newly built backend. This isn't necessary since we build and/or install the backend every time we run a build. There's no need for the dependency to get tracked in the lock file.

**Comment by pierr3** [comment]
This is expected behaviour and not an issue, there is no workaround.
