### ISSUE TITLE
[1.3.0 bX] Mini mode "always on top in mini mode" not "always on top"

### ISSUE THREAD

**Issue by Ades128** [pierr3/TrackAudio#207]
With the new UI if "keep windows on top" is selected "always", the window is always on top also in mini mode.
Is "in mini mode" is selected the mini mode don't stay on top.
Nothing in log unfortunately.

Still using:
6.11.6-arch1-1
pipewire-pulse 1:1.2.6-1
alsa-utils 1.2.12-1
gnome 47.0.1
xorg-server 21.1.14-1
libpulse 17.0-3

**Comment by pierr3** [comment]
@neilenns can you look at that by any chance?

**Comment by neilenns** [comment]
@Ades128 Can you confirm this worked for you on b3?

**Comment by Ades128** [comment]
@neilenns  sorry to not have thought about that initially.

1.2.0 works but from 1.3.0 b1 it's the same as described above. (I tested each beta)

**Comment by neilenns** [comment]
Thanks! I'll have to chat with @GeorgeBarlow about this a bit.
