### ISSUE TITLE
Client not receiving

### ISSUE THREAD

**Issue by Ninovui** [pierr3/TrackAudio#208]
Traffic can't be heard with the new beta.3 update. Reverted to Beta.2.
I don't know why I can't hear other people on frequency...

**Comment by neilenns** [comment]
FWIW I've had this issue twice in the last week as well. The last RX shows someone called, but I do not hear anything. People can hear me fine.

**Comment by GeorgeBarlow** [comment]
Is this still a recurring issue or does it seem that it has been resolved?

**Comment by pierr3** [comment]
Please report if this has been fixed in the latest beta

**Comment by pierr3** [comment]
Closing for now, please report if this comes back
