### ISSUE TITLE
Document the need for speaker device

### ISSUE THREAD

**Issue by Epse** [pierr3/TrackAudio#209]
I was recently helping someone set up TrackAudio (both beta2 and beta3) and they could not get audio output. The UI shows receive functioning, but no sound.

We eventually figured out that when only an audio output device is selected, but no speaker device; no sound will play even when the SPK button is deselected.

If this is not a bug, might be helpful to document or have the settings UI note this behaviour.

**Comment by Ades128** [comment]
hello, could you provide trackaudio.log file please

**Comment by pierr3** [comment]
Will be fixed in next version

**Comment by Epse** [comment]
Amazing, thank you so much
