### ISSUE TITLE
[Input system] Unable to assign PTT / Unreliable key hit detection

### ISSUE THREAD

**Issue by pierr3** [pierr3/TrackAudio#211]
The input system is unreliable, causing the following issues:
- Many users mostly on windows are unable to set a Ptt key as a "ghost" key gets set immediately upon clicking "Set new Ptt".
- Some users are reporting that key presses are only detected when the window is focused.
- The keybind system depends on X11 on windows and thus prevents TrackAudio from running on Wayland native.

**Comment by GeorgeBarlow** [comment]
I think you what time it is 🎆 libuiohook 🎆

**Comment by neilenns** [comment]
> I think you what time it is 🎆 libuiohook 🎆 

🥳🥳🥳🥳🥳

**Comment by GeorgeBarlow** [comment]
> I can not use trackaudio on beta3 - only getting stuck mic on frequency, without even showing that I am transmitting on my side.

https://github.com/pierr3/TrackAudio/pull/214

**Comment by GeorgeBarlow** [comment]
This issue should be addressed in the upcoming beta 4 release.
