### ISSUE TITLE
Issue with the new PTT System and X52

### ISSUE THREAD

**Issue by Octonath** [pierr3/TrackAudio#230]
Hey I got an X52 joystick and I've got issue setting up PTT with it connected that I didn't have before. The X52 has a "Mode" switch which means that one button is always "pressed", either 24,  25 or 26 is always pressed.
![controls](https://github.com/user-attachments/assets/7c035fe1-15ca-45ef-b341-d6f8b6703f82)

**Comment by GeorgeBarlow** [comment]
Can you give more detail, I'm struggling to understand the full extent of the issue. However, if you see the release notes for b4 (which is the version I assume you're on) the Joystick PTT remains the same implementation that was found in previous versions it was only the keyboard PTT system that was overhauled.

**Comment by pierr3** [comment]
If you Ptt is always pressing, then it will pick it up in any case, it's not really a TrackAudio problem, more of a system problem, maybe there is a way in Windows to ignore this press? If you want to set a keyboard ptt, then disconnect your joystick first and it should work. If you want to use a button on your joystick, you could map the button press to a key, and then use the set keyboard key.

**Comment by Octonath** [comment]
Yeah if there is no way to ignore this button then I'll just need to disconnect the joystick. Reported it just in case
