### ISSUE TITLE
[release 1.3.0 b4] follow previous "Make always on top work properly on Arch Linux" #207 #216

### ISSUE THREAD

**Issue by Ades128** [pierr3/TrackAudio#231]
using:
6.12.1-arch1
gnome 47.0.2
xorg-server 21.1.14-1

Still the same even with transparency activated.

**Comment by GeorgeBarlow** [comment]
This seems to be an upstream issue due to the way Electron handles alwaysOnTop on Linux in general. I'll update the README to reflect this issue being highlighted, but there is not much we can do until they come up with a solution and push it down to us. 

Thank you for raising it though!
