### ISSUE TITLE
[FEAR REQ] Switching window button under minimize mode

### ISSUE THREAD

**Issue by AaronZSAM101** [pierr3/TrackAudio#235]
Hi there,
Is there any possible to add a button to switch the window mode(normal and minimize) under minimize mode? 
![image](https://github.com/user-attachments/assets/c06b929a-4cd4-4397-b225-9e0fea7b40ab)
For example, If I need to switch to normal window for some operation, I need to drag the window for a large scale on my screen. The experience would be enhanced I thought if there is a button on the minimize window, once the user click, it can switch to the normal window.

Thanks in advance~

**Comment by neilenns** [comment]
If you mouse over the minimized window a restore button will appear in the top right corner

**Comment by AaronZSAM101** [comment]
> If you mouse over the minimized window a restore button will appear in the top right corner

Yes I found that, so I closed the issue..
