### ISSUE TITLE
Unstable Slurper connection

### ISSUE THREAD

**Issue by Atriusftw** [pierr3/TrackAudio#239]
Using 1.4.0-beta4 currently, but had the same issue with latest stable version.
TrackAudio feels much more unstable than AFV and i more frequently get disconnected from Slurper.

Logfile attached where this happened two times during a session.

[trackaudio.log](https://github.com/user-attachments/files/18065936/trackaudio.log)

**Comment by pierr3** [comment]
Looking at your log this is not a TrackAudio issue, the server was returning an error (also reported on discord). The difference with AFV Windows is that it checks the slurper less often, so there is a longer delay when the slurper goes down and the client picks it up, but your total down time would be the same.
