### ISSUE TITLE
TrackAudio or the RDF Plugin crashes Euroscope

### ISSUE THREAD

**Issue by GeheimagentNr1** [pierr3/TrackAudio#243]
TrackAudio: 1.3.0-beta.4
RDF Plugin: 1.4.0
EuroScope: 3.2.9

Sometimes when removing the RX for a station, it crashes the main EuroScope instance.
It does happen every time, but it is always a lottery, when removing RX.

Sometimes there is an error message with invalid parameters shown from EuroScope, when removing the RX, but in these cases EuroScope does not crash.

(I don't remember any more, if I also had this issue, when adding RX or XC for a station)

Is there a way, this could be checked with logs or something?
If yes, where can the logs be found?

**Comment by pierr3** [comment]
This is an issue for the RDF plugin and not trackaudio, please open an issue there and hopefully @KingFuchChan can fix it
