### ISSUE TITLE
Unable to communicate with all aircraft in coverage area

### ISSUE THREAD

**Issue by neilenns** [pierr3/TrackAudio#28]
This was reported by a visiting controller in the ZSE Discord. They don't GitHub so opening on their behalf.

Original report: "I tried this [TrackAudio] and for me on center 1 out of 10 pilots can hear me." They usually use AFV and have never used VectorAudio before. I followed up with additional questions, here's some more details.

Controller was connected as DEN_17_CTR. It didn't automatically load the station so he manually added DEN_17_CTR and eanbled Tx/Rx. There were aircraft that should be in the coverage area but the controller was unable to hear or speak to them. Two planes near the border of ZLA came through fine, but there was another one in the same area that couldn't be reached.

Let me know if you need more info and I can ask.

**Comment by neilenns** [comment]
They were using TrackAudio. I asked if they'd ever used VectorAudio to see if they'd had the issue there as well but the answer was no, they'd never used VA. 

I can ask them to check transceiver count next time they control, and to try hitting XC.

**Comment by pierr3** [comment]
This should be fixed in latest version where transceivers where not properly used. If that happens again, try to RX off and on again. Closing this since no further reports
