### ISSUE TITLE
Update eslint to run with increased coverage

### ISSUE THREAD

**Issue by neilenns** [pierr3/TrackAudio#29]
Just puttering about on a Tuesday afternoon to try and get some more opinionated eslint rules running since I wasn't feeling like controlling.

It was quite a bit of tweaking so I figured I would document what I did here. No PR forthcoming, these changes are quite a few package upgrades and result in a TON of eslint errors to fix. Mostly just documenting so you have the steps I did available if/when you decide to add more rules.

1. Upgrade to TypeScript 5.4.5
2. Upgrade to eslint 8.57.0
3. Upgrade to @typescript-eslint/eslint-plugin 7.8.0
4. Add the `semistandard` npm package as a dev dependency to the top-level package.json. This resolved errors from eslint somewhere deep in the vcpkg stuff. Feels like it was a hack, it probably belongs in another package.json somewhere that I don't know about.
5.  Add `"strictNullChecks": true` to the tsconfig
6. Switch to a `.eslintrc.cjs` config file format instead of json
7. Change the lint command in package.json to `"lint": "eslint .",`. TBH I'm not sure this was necessary.
7. Use the `strict-type-checked` rules with the following modified config:

```javascript
/* eslint-env node */

module.exports = {
  env: { browser: true, es6: true, node: true },
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/strict-type-checked",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaVersion: "latest",
    sourceType: "module",
    project: true,
    tsconfigRootDir: __dirname,
  },
  ignorePatterns: ["webpack.*.ts", "forge.config.ts", ".eslintrc.cjs"],
};
```

The result is 251 problems 😯😂 Here's an example in vscode:

![image](https://github.com/pierr3/TrackAudio/assets/9524118/54c0f8bc-74af-4e1c-8a55-c9949367bee2)

**Comment by neilenns** [comment]
Changes are [pushed to a branch](https://github.com/neilenns/TrackAudio/tree/neilenns/issue29) if you want to try them out in a dev container/github codespace. I don't recommend trying it on your regular dev environment since it messes with a bunch of package versions.

**Comment by pierr3** [comment]
Thanks, let me have a look. It'd be better to exclude the whole backend/ folder from eslint (except maybe the types/ folder), as the C++ formatting will use clang-tidy and clang-format

**Comment by neilenns** [comment]
Can probably just add "backend/" to the excluded list then.

**Comment by pierr3** [comment]
That should do it, check the latest commits

**Comment by pierr3** [comment]
This has been implemented
