### ISSUE TITLE
Add support for AFV-style custom stations

### ISSUE THREAD

**Issue by lightbord** [pierr3/TrackAudio#33]
Currently AFV allows you to add a custom station at a specific airport with the ** syntax (for example **KLAX_X_TWR). This creates a transceiver at the airport location, asks you for the frequency, and if you are signed on to at least that level, allows you to transmit on it. A similar function will ask you for the frequency when entering an unknown callsign that is connected to the network but not in the database. This functionality is particularly useful for adding ATISes that may not be in the database so you can test if they are transmitting correctly. Using the "add custom VHF frequency" function doesn't seem to work for this (tested while observing Center), perhaps because the vis center isn't near the airport, so it would be great to be able to specify the location of the transceiver as described.

**Comment by pierr3** [comment]
What’s the use case for this? Can you not just add the station callsign?

**Comment by lightbord** [comment]
As I mentioned, some stations that are online aren't in the AFV database. A lot of airport's ATISes are not in there, for example. I tried adding several ATISes yesterday and none of them.

**Comment by pierr3** [comment]
The issue is that this is not standard. The AFV manual states that all stations, including atises, should be defined in database. The first recourse before looking at this feature is to ask your FE to add the atises in database

**Comment by pierr3** [comment]
After some thinking, this will not be added, rather, please use the prescribed requirements of the AFV Facility Engineer Manual of defining stations in database
