### ISSUE TITLE
ATC control lower position can transmit in in Higher Position's frequency

### ISSUE THREAD

**Issue by XuanyanYe** [pierr3/TrackAudio#34]
Hello!

Today I was using Track Audio controlling ZSAM_RMP, but I can transmit in ZSHA_CTR and ZSAM_TWR‘s frequency, not sure if it is OK but in Audio For VATSIM client this is not allowed since from down to up control is not OK on VATSIM.

Thanks for looking into this

**Comment by pierr3** [comment]
It's correctly implemented and works as intended. The restriction in AFV Windows is not really necessary. Contact a supervisor if a controller is abusing this.
