### ISSUE TITLE
Wrong PTT Button Detected

### ISSUE THREAD

**Issue by uetcis** [pierr3/TrackAudio#37]
For some keys, the detected key shown in TrackAudio is different from what is actually pressed.

Environment: Linux, Xwayland, All recent TrackAudio commits

E.g. When I press the right control on my laptop, TrackAudio detects the PageDown key instead.
![image](https://github.com/pierr3/TrackAudio/assets/25654046/eab79916-ba75-4ca0-ad82-b6916c16f35a)

**Comment by uetcis** [comment]
VectorAudio does not have this issue

**Comment by herver** [comment]
Could you try pressing the "correct" mapped key and the "wrong" key with `xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'` and `wev | grep 'sym'` (native Wayland) to see whether key mapping works correctly ?

**Comment by uetcis** [comment]
Xev output:
192 XF86Launch5 (trackaudio sees as KP_Enter)
104 KP_Enter
105 Control_R (trackaudio sees as Next)
117 Next

Wev output:
                      sym: XF86Launch5  (269025093), utf8: ''
                      sym: KP_Enter     (65421), utf8: '\r'
                      sym: Control_R    (65508), utf8: ''
                      sym: Next         (65366), utf8: ''

**Comment by pierr3** [comment]
Does the key you select actually work though? The display of the key name is a bit clunky and uses a manual mapping, ie this: https://github.com/pierr3/TrackAudio/blob/main/src/helper.ts

It's possible that the mapping is offset on certain versions of XWayland

**Comment by uetcis** [comment]
> Does the key you select actually work though? The display of the key name is a bit clunky and uses a manual mapping, ie this: https://github.com/pierr3/TrackAudio/blob/main/src/helper.ts
> 
> It's possible that the mapping is offset on certain versions of XWayland

I was trying to use XF86Launch5 as PTT but it really got detected by trackaudio as the numpad enter key to the extent that pressing XF86Launch5 results in the action of pressing enter on the UI buttons in trackaudio. So it’s not usable.

**Comment by pierr3** [comment]
Please try the latest version, this should be fixed

**Comment by pierr3** [comment]
Closing for now, please comment if this is still an issue
