### ISSUE TITLE
Cannot get data from the slurper

### ISSUE THREAD

**Issue by Ades128** [pierr3/TrackAudio#38]
I put it here as a new issue

using last commit on Arch linux via AUR trackaudio-git

At the start of TrackAudio I receive this "notification"
```
[1855Z] Error while parsing slurper data, check the log file. This means your internet may be down or the VATSIM servers may experience an outage. You will not be able to connect until this is resolved. TrackAudio will keep retrying in the background.
```

Log:
```
20:49:54.776826689 [22561] RemoteData.hpp:57            LOG_ERROR     trackaudio_logger Cannot get data from the slurper. Object is null.
```
https://slurper.vatsim.net/users/info/?cid=1572048 is:
```
1572048,LFMN__APP,atc,134.475,120,43.66541,7.21498,0,0,0,0,0,0,0,0,
```
Also tested using VectorAudio, works well.

curl -4 and curl -6 work.

_Originally posted by @Ades128 in https://github.com/pierr3/TrackAudio/issues/30#issuecomment-2091368306_

**Comment by pierr3** [comment]
Any firewall setup? Permission of the executable? ufw setup? There is no particular reason as to why this would fail on your system, or why this would work in VA. The code between VA and TA for this particular feature is verbatim the same, as well as the way the library is linked.

**Comment by Ades128** [comment]
**Any firewall setup?** no modifications, worked before
**Permission of the executable?** using yay to manage AUR package, shouldn't be any issues about permissions, worked on previous versions.
**ufw ?** not in use
I'm agree that it shouldn't be any particular reason.

I tried on my laptop (same system configuration), it works.
I need to dig, specially because previous TA versions worked without any modification on the configuration.
I'll keep you in touch.

**Comment by Ades128** [comment]
update:

yesterday night i was able to use Trackaudio after a new clean build.
Today I made a new clean build to add last commits and now I don't have any messages neither errors on LOG file,
but it doesn't recognize my ES connection.

Vectoraudio still working

```
1572048,LFPG_APP,atc,121.155,120,49.00975,2.54782,0,0,0,0,0,0,0,0,
1572048,LFPB_ATIS,atc,120.000,50,48.96945,2.44139,0,0,0,0,0,0,0,0,
```

![image](https://github.com/pierr3/TrackAudio/assets/145056592/0983e2a4-7c98-4b11-8da3-0a5d97584d75)

**Comment by pierr3** [comment]
Oh yea don’t get fooled by the success of the CI, it’s currently broken
haha, do a clean build with previous commits. Don’t consider anything on
master as stable yet (will switch to dev branch model post beta).

**Comment by pierr3** [comment]
also make sure that your CID is properly set! Possible that you config got deleted somehow

**Comment by Ades128** [comment]
no more issue with latest release
