### ISSUE TITLE
Mini-mode toggle

### ISSUE THREAD

**Issue by Chopan22** [pierr3/TrackAudio#39]
Just curious if it is possible to implement a mini-mode toggle button. To be clear, a button that when clicked toggles between a "normal" size window and a mini-mode sized widow.

**Comment by pierr3** [comment]
Yes, that'd be easy to add, but I need to find a space in the UI to add this, it's getting busy

**Comment by neilenns** [comment]
@Chopan22 Are you asking for a mini mode generally? Or a button to toggle to the existing mini mode you can access by resizing the window down smaller?

**Comment by Chopan22** [comment]
A button to toggle it. A similar idea could be the vATIS way to toggle their "Mini-Display".

**Comment by RudiZhang** [comment]
a TX RX button on the mini mode will also be very useful

**Comment by pierr3** [comment]
TX RX button is out of scope of mini mode, otherwise mini mode will become maxi mode in two seconds

**Comment by RudiZhang** [comment]
how about to use frequency instead of MANUAL in mini mode?

**Comment by pierr3** [comment]
Yes, good idea - will fix

**Comment by bostjanlaba** [comment]
There is a mini-mode available? How do I switch to mini-mode?

**Comment by pierr3** [comment]
Resize the window very small

**Comment by pierr3** [comment]
Added
