### ISSUE TITLE
Windows Defender Flagging a Trojan

### ISSUE THREAD

**Issue by Hypekingfish** [pierr3/TrackAudio#4]
windows defender falsely flagged a trojan for trackaudio

**Comment by pierr3** [comment]
Thanks, it probably does this because the programme listens to key input globally for push to talk. I need to find a way to not flag it as such

**Comment by neilenns** [comment]
I'm getting this today for some reason, even though it was fine yesterday. The specific report is:

```
Trojan:Script/Phonzy.A!ml
file: C:\Users\neile\Downloads\trackaudio-win32-x64-1.0.1\opus.dll
```

**Comment by pierr3** [comment]
Very very strange that this is on opus, it’s a really common audio codec.
I’ll investigate.

**Comment by pierr3** [comment]
Does the latest version also do that?

**Comment by neilenns** [comment]
I'll check later today. I excluded the folder from Windows Defender so I'll have to re-enable it.

**Comment by neilenns** [comment]
This does appear to work now. How'd you fix it?

**Comment by pierr3** [comment]
I did nothing haha, let's see if it lasts, closing for now
