### ISSUE TITLE
Delete a station

### ISSUE THREAD

**Issue by Chopan22** [pierr3/TrackAudio#40]
I like how it gets all related callsigns when adding a new station, however in order to keep it clean it'd be nice to be able to delete a station from the listed ones selecting it and pressing either delete or backspace. Another possible way could be to delete a station when clicking on it while pressing alt or some other key.

**Comment by pierr3** [comment]
You can delete a station by click it. and then hitting delete on the right sidebar. I will add a keyboard shortcut as this may be useful.

**Comment by maxlk96** [comment]
As an alternative to a keyboard shourtcut, maybe adding a right click context menu with a delete option would be possible?

**Comment by pierr3** [comment]
Is the current system that annoying that it requires a new feature ?

**Comment by maxlk96** [comment]
> Is the current system that annoying that it requires a new feature ?

For me personally, yes. I really miss the way it was done in VectorAudio.

Also the option to activate TX/RX/XC all at once was very convenient, as in the AFV client. One (right or left) click on XC enables all three, one click on RX deactivates all three.

**Comment by Chopan22** [comment]
> Is the current system that annoying that it requires a new feature ?

I see it as a sort of "quality of life" change

**Comment by pierr3** [comment]
in the next release, you'll be able to click a frequency then hit "Delete" or "Backspace" to delete it. The behaviour you describe @maxlk96 around XC/TX is also implemented
