### ISSUE TITLE
beta3 installer: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by RudiZhang** [pierr3/TrackAudio#42]
![image](https://github.com/pierr3/TrackAudio/assets/40914896/f064eaaf-744f-41a6-9e0f-f153ae37bcb3)

**Comment by RudiZhang** [comment]
same for zip

A temporary solution is to install beta2 first and then overwrite beta3

**Comment by neilenns** [comment]
I get this as well on Windows.

**Comment by zladatm** [comment]
> I get this as well on Windows. It winds up leaving a TrackAudio process running that you have to kill via Task Manager.

Yup, I ended up with 3 instances of it in the task manager. I installed beta3 by copying the contents of the .zip to the existing install I had.

**Comment by pierr3** [comment]
Thanks all, identified the problem as the afv native DLLs not being copied.
I will release a new version today.

**Comment by pierr3** [comment]
This is fixed in beta.5!
