### ISSUE TITLE
Adding a station that has the same frequency as the input callsign does nothing.

### ISSUE THREAD

**Issue by VeIocityy** [pierr3/TrackAudio#43]
https://gyazo.com/c5568d9569a4aae8ae1744cba34fc1e4
Not sure if this is intentional functionality.

**Comment by pierr3** [comment]
Thanks for the great gif, yes, you are only allowed to have one of the same frequency. You should always use the station callsign where possible

**Comment by VeIocityy** [comment]
Understood, perhaps overwrite the manual entry with the callsign?
