### ISSUE TITLE
Joystick PTT name not recognized/displayed

### ISSUE THREAD

**Issue by kengreim** [pierr3/TrackAudio#44]
I use vJoy (virtual joystick) as my PTT, which has worked across the AFV standalone client and Vector Audio. I trigger the vJoy button via a Streamdeck Pedal button (using a Streamdeck vJoy plugin).

After attempting to set PTT on TrackAudio with the new joystick support, I still see "Ptt: Not Set"
![image](https://github.com/pierr3/TrackAudio/assets/34892440/ae379058-0622-4a9d-9e0a-a6b383605a03)

**However**, when I press the foot pedal PTT, the "Set new PTT" button does light up, which suggests to me that TrackAudio is properly capturing the vJoy button press at least? I haven't tried it on the network yet.
![image](https://github.com/pierr3/TrackAudio/assets/34892440/5575d117-4ab0-4399-9738-48e1c5318c19)

Fresh log:
```
20:11:40.423148904 [1560856] InputHandler.cpp:113         LOG_INFO      trackaudio_logger Forwarding Ptt Key Name Not Set
20:11:43.402948237 [1324556] RemoteData.cpp:56            LOG_INFO      trackaudio_logger Slurper is back online.
20:11:45.573166709 [1561140] InputHandler.cpp:68          LOG_INFO      trackaudio_logger Joystick Ptt Key set: 0 on Joystick 0
20:11:45.573494028 [1561140] InputHandler.cpp:113         LOG_INFO      trackaudio_logger Forwarding Ptt Key Name Not Set
20:11:47.986698657 [1560856] main.cpp:749                 LOG_INFO      trackaudio_logger Exiting TrackAudio
```

**Comment by pierr3** [comment]
Seems to have worked, try and restart TrackAudio and see if you get the proper key description. It could be that your virtual joystick does not properly propagate its device name, I will need to investigate why the UI does this. If the Pat button lights up orange, then it should work on the network

**Comment by pierr3** [comment]
Nevermind it was my fault, fixed is pushed, will be available in the next release - your Ptt is setup fine and will work
