### ISSUE TITLE
Crash on startup ver. 1.0.2_beta.4-2 (AUR)

### ISSUE THREAD

**Issue by EmilianSpo** [pierr3/TrackAudio#45]
![image](https://github.com/pierr3/TrackAudio/assets/10565605/7d09baf9-a0b7-4762-971b-287981b02465)

~5 seconds after startup, just upgraded

TrackAudio.log
```
11:36:42.486292221 [15526] main.cpp:667                 LOG_ERROR     trackaudio_logger Mandatory update required: 1.0.2-beta.2 -> 1.0.2-beta.4
11:39:24.457531609 [22798] Shared.hpp:102               LOG_WARNING   trackaudio_logger Settings.ini file not found, creating it
11:39:24.960688964 [22798] InputHandler.cpp:113         LOG_INFO      trackaudio_logger Forwarding Ptt Key Name Unknown Scancode
```

Settings.ini
```
[Ptt]
PttKey = -1
JoystickId = 0
isJoystickButton = false
```

**Comment by EmilianSpo** [comment]
~5 seconds after startup

**Comment by pierr3** [comment]
Can you specify type of installation ? (deb, manual build, app image), and
OS details including distro and architecture ?

**Comment by EmilianSpo** [comment]
![image](https://github.com/pierr3/TrackAudio/assets/10565605/38f7ac3e-7bac-4715-9d36-613b42b06961)

AUR install via pamac-gtk

**Comment by EmilianSpo** [comment]
Same issue for the AppImage

![image](https://github.com/pierr3/TrackAudio/assets/10565605/580e0f3d-83ca-45ed-95ed-e6a9a7707bb6)

**Comment by pierr3** [comment]
Can you share the coredump file? You can use coredumpctl info <pid/timestamp> to get it right after the crash

**Comment by EmilianSpo** [comment]
`           PID: 8872 (trackaudio)
           UID: 1000 (emilian)
           GID: 1000 (emilian)
        Signal: 11 (SEGV)
     Timestamp: Sun 2024-05-12 12:00:28 CEST (4s ago)
  Command Line: /usr/lib/trackaudio/trackaudio
    Executable: /usr/lib/trackaudio/trackaudio
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-gnome-trackaudio-8872.scope
          Unit: user@1000.service
     User Unit: app-gnome-trackaudio-8872.scope
         Slice: user-1000.slice
     Owner UID: 1000 (emilian)
       Boot ID: a7da05e535b6484eb005437881d015d8
    Machine ID: 5062bf8ca43a405c8edbc4c6b7852ffc
      Hostname: emilian-manjaro
       Storage: /var/lib/systemd/coredump/core.trackaudio.1000.a7da05e535b6484eb005437881d015d8.8872.1715508028000000.zst (present)
  Size on Disk: 8.6M
       Message: Process 8872 (trackaudio) of user 1000 dumped core.
                
                Stack trace of thread 8925:
                #0  0x00007f8c39741b71 EC_KEY_free (libafv_native.so + 0x2b7b71)
                #1  0x00007f8c39769d62 EVP_PKEY_free (libafv_native.so + 0x2dfd62)
                #2  0x00007f8c397a833a n/a (libafv_native.so + 0x31e33a)
                #3  0x00007f8c3983e2b1 ossl_asn1_template_free (libafv_native.so + 0x3b42b1)
                #4  0x00007f8c3983dfd8 ossl_asn1_item_embed_free (libafv_native.so + 0x3b3fd8)
                #5  0x00007f8c3983e2b1 ossl_asn1_template_free (libafv_native.so + 0x3b42b1)
                #6  0x00007f8c3983dfd8 ossl_asn1_item_embed_free (libafv_native.so + 0x3b3fd8)
                #7  0x00007f8c3983e1d9 ASN1_item_free (libafv_native.so + 0x3b41d9)
                #8  0x00007f8c397a55a3 OPENSSL_sk_pop_free (libafv_native.so + 0x31b5a3)
                #9  0x00007f8c39b5e41a ossl_ssl_connection_free (libafv_native.so + 0x6d441a)
                #10 0x00007f8c39b5d5f5 SSL_free (libafv_native.so + 0x6d35f5)
                #11 0x00007f8c39f6895a n/a (/tmp/.org.chromium.Chromium.X1T2iW + 0x14d95a)
                ELF object binary architecture: AMD x86-64
`

**Comment by pierr3** [comment]
Do you have any proxy, or other firewall or special network configuration? This is the backend failing to reach the AFV API

**Comment by pierr3** [comment]
Actually this may be something silly, have you upgraded to beta 4? Your log file shows:

```trackaudio_logger Mandatory update required: 1.0.2-beta.2 -> 1.0.2-beta.4```

**Comment by EmilianSpo** [comment]
> Do you have any proxy, or other firewall or special network configuration? This is the backend failing to reach the AFV API

No, VectorAudio works fine and the previous version of TrackAudio did as well. I have not changed any network/firewall settings nor am I using a proxy.

**Comment by EmilianSpo** [comment]
Manjaro just released a system update, and when I upgraded my system TrackAudio starts fine. So I will close this issue, though I have no idea how it fixed itself. Thanks for the support though!
