### ISSUE TITLE
Remember window position

### ISSUE THREAD

**Issue by sheza5** [pierr3/TrackAudio#46]
If possible could a feature similar to AFV be implemented where the previous placement of Trackaudio before closed is remembered. I keep having to open the window and then reposition it to the top where it does not overlap other windows. This would also apply to mini-mode if possible. Thanks.

**Comment by neilenns** [comment]
I've implemented this for another Electron project in the past @pierr3, you can see the code here: https://github.com/neilenns/vatsim-site-wrapper/blob/main/src/main.ts. It's... ok. I never got remembering the maximized state to work correctly.

**Comment by sheza5** [comment]
I am not a code person so what would I be looking to do with code? Copy it somewhere?

**Comment by neilenns** [comment]
My comment was for Pierre

**Comment by pierr3** [comment]
Implemented in next version
