### ISSUE TITLE
Set PPT bug

### ISSUE THREAD

**Issue by Chopan22** [pierr3/TrackAudio#48]
When trying to set a new PPT on the settings it detects "BLOQ NUM" as always pressed, but if I keep that PPT it doesn't actually work on frequency. I can select another PPT by clicking to select a new one and then quickly press the key I want.

Windows 11 using the extracted zip beta.4

**Comment by pierr3** [comment]
You'll need to check your peripherals, this is not going to be a TrackAudio issue but someone on your system firing a key press all the time.
