### ISSUE TITLE
Add websocket message for enabling/disabling station tx/rx/xc

### ISSUE THREAD

**Issue by neilenns** [pierr3/TrackAudio#52]
I'd like to be able to POST to an endpoint to enable/disable TX/RX for a station.

The use case is to create a StreamDeck button that will call the endpoint when pressed to enable/disable secondary stations that I listen to on the side but may want to turn off when they get busy. Something like `POST /station` with a JSON body like this:

```javascript
{
   "pCallsign": "SEA_GND",
   "tx": false, // or true to enable or undefined to leave as-is
   "rx": false, // or true to enable or undefined to leave as-is
   "xc": false // or true to enable or undefined to leave as-is
}
```

**Comment by neilenns** [comment]
Thinking about this a bit more, for my use case, I'd need a way to toggle the state of Rx without knowing the current state of the frequency. Maybe that could just be a GET request like this `/Rx/toggle/SEA_GND` or similar?

**Comment by pierr3** [comment]
So the HTTP endpoint is deprecated, everything should go through WebSocket now, so we can add something like this in the web socket protocol if you prefer.

**Comment by neilenns** [comment]
I updated the title to say websocket 😀

**Comment by bostjanlaba** [comment]
I like this idea aswell! +1
