### ISSUE TITLE
Add HTTP endpoint for getting current status for a specific station

### ISSUE THREAD

**Issue by neilenns** [pierr3/TrackAudio#53]
At the moment there's an `/rx` and a `/tx` endpoint which returns a comma delimited list of frequencies with RX or TX enabled. Unfortunately this can't be parsed with JSON parsing on the receiving end. Use case is to set the state/icon of a Streamdeck button to match whether TX is enabled for a given station.

I'd like an endpoint that instead takes a specific station and returns a JSON object indicating the status of the station. Something like `GET /status/SEA_GND` that returns something like this:

```javascript
{
   "pCallsign": "SEA_GND",
   "tx": false, // or true if on
   "rx": false, // or true if on
   "xc": false // or true if on
}
```

**Comment by pierr3** [comment]
Same thing, the web socket server already broadcasts frequency status automatically, on logon and at every change in JSON format, see the wiki article for that

**Comment by neilenns** [comment]
Hmm. I'm not sure I can use the web socket endpoint though :( I'll have to see.

**Comment by pierr3** [comment]
You can! Check this out, it'd be a similar structure, not exactly the same though: https://github.com/pierr3/deckfcu
