### ISSUE TITLE
Set PTT key issue

### ISSUE THREAD

**Issue by bostjanlaba** [pierr3/TrackAudio#56]
One user in our vACC is reporting an issue trying to set CTRL or SHIFT or some modifier key as PTT KEY. While on my PC it normally shows "press a key" to set it up, in his case this is shown only briefly and then it picks up NUM_LOCK key. He can set some key like A,B,C, space. But CTRL, SHIFT, ALT...result in NUMLOCK always.

Any idea why or what's the solution?

Thanks

**Comment by proviancy** [comment]
Same issue here

**Comment by pierr3** [comment]
Does the Ptt actually work when you press the key you want ? As in is it
just a display issue or the key not picked up at all. Can you share what os
you are on and if you use any special peripheral? If you have joysticks
plugged in, try to unplug everything and then set your Ptt key.

**Comment by bostjanlaba** [comment]
Yes, I can confirm disconnecting joystick is a solution in this case.

**Comment by pierr3** [comment]
Please ensure that you then disconnect any device that is rapidly pressing a key, this is not something that I can fix if your system is getting spammed with key calls
