### ISSUE TITLE
Always on top prevents app from dispaying

### ISSUE THREAD

**Issue by iFrezeTiger** [pierr3/TrackAudio#57]
Whenever I turn on "Keep window on top" the app goes to the taskbar and I can't open it, then I have to restart the app and I can only have it displayed until I minimize it for the first time, and then the same thing happens, the app gets stuck on the taskbar.

Edition	Windows 11 Home
Version	23H2
Installed on	‎06/‎12/‎2023
OS build	22635.3575
Experience	Windows Feature Experience Pack 1000.22700.1011.0

**Comment by pierr3** [comment]
Will investigate but this is not due to Trackaudio itself, rather the underlying libraries

**Comment by pierr3** [comment]
Any changes since the latest release?

**Comment by iFrezeTiger** [comment]
Seems to be working fine now

**Comment by pierr3** [comment]
Fantastic thanks
