### ISSUE TITLE
Allow binding a separate PTT key per frequency

### ISSUE THREAD

**Issue by Jonhasacat** [pierr3/TrackAudio#59]
As simple as it sounds. 

Allow specifiying a separate PTT key for an individual frequency. If none is specified, they should all use the 'global' PTT binding.

This would be useful for things like controller shoutlines and also when covering a frequency for another controller for a limited time.

**Comment by pierr3** [comment]
Thanks for the suggestion, unfortunately this will not be implemented in
this project.

**Comment by iFrezeTiger** [comment]
Hey, I just had this same idea and found this request, any chance you could reconsider adding it? I think it could be even more useful now as GUARD is allowed on the network.

**Comment by pierr3** [comment]
It's unfortunately not technically possible with the current implementation, so will not be able to implement for the time being
