### ISSUE TITLE
TrackAudio randomly disconnected

### ISSUE THREAD

**Issue by neilenns** [pierr3/TrackAudio#6]
Another "sorry I don't have a repo for this" issue.

Was controlling today and eventually tower told me that a plane on the ground wasn't getting any answer from me on frequency. Turns out TrackAudio had just disconnected. No idea why, CRC was still connected fine. Hitting the connect button reconnected me fine and I was good to go again.

**Comment by pierr3** [comment]
Did you not get the notification sound or an error message? Was it just
disconnected ?

**Comment by neilenns** [comment]
There was no error message in the app when I flipped back to it. I don't know if there was a sound, there are so many apps that make a sound on vatism I tend to ignore them all, plus my headset blocks a lot of them out :(

**Comment by pierr3** [comment]
I'll make sure there is no code out there that doesn't post an error message

**Comment by neilenns** [comment]
This happened again yesterday.

I'm 99% sure it's because I swapped positions and forgot to hit the connect button 😬 😳 🙈

**Comment by pierr3** [comment]
Ah perf, that's exactly it as there is an auto disconnect built in if you switch positions. I just forgot to throw in an error message when this happens!

**Comment by KingfuChan** [comment]
I think I have encountered same issue. No prompt for error or sound, just I'm unable to receive and transmit. I can only see it from my RDF plugin which tells me no active station.

**Comment by neilenns** [comment]
> I think I have encountered same issue. No prompt for error or sound, just I'm unable to receive and transmit. I can only see it from my RDF plugin which tells me no active station.

That sounds like a different problem than the one I reported. In my case TrackAudio clearly shows it isn't connected at all.

**Comment by pierr3** [comment]
So there is supposed to already be an error if have a change during an active session. What I suspect is that you disconnected for long enough so that it just picked up a normal disconnection, for which there is no error message. I will fix that
