### ISSUE TITLE
connecting to stations not set up in AfV database

### ISSUE THREAD

**Issue by capzDE** [pierr3/TrackAudio#69]
TrackAudio prevents connections to stations whose login is not set up in the AfV database with a "Station not found" error. This creates problems when controllers are taking over a position from another controller who was using the default login as they will have to use a different login to connect: e.g., if ABCD_APP is the default login and already online, a relieving controller logging in as ABCD_1_APP would be unable to connect with TrackAudio.
The AfV Standalone client (and I believe the same was true for VectorAudio) would always connect regardless and set the primary frequency selected in the ATC client. A similar functionality in TrackAudio would be greatly appreciated.

**Comment by pierr3** [comment]
Again, this will not be supported - you need to talk to your facility engineer. All stations should be defined in database, no exceptions. To clarify, the software will connect fine, but you'll need to manually add your station
