### ISSUE TITLE
Cross couple continues to transmit after deselecting

### ISSUE THREAD

**Issue by luke11brown** [pierr3/TrackAudio#7]
After deselecting cross coupling, other controller could still here my transmissions on their frequency

**Comment by pierr3** [comment]
If anyone also experiences this, please report

**Comment by Querbahn** [comment]
Hi, 

I had the same issue with the first beta version (thereafter I didn't try to replicate it - no occasion). I was connected as _GND and wanted to listen to the _TWR. I accidentally selected TX on his frequency for a short moment. The Tower could here my transmissions (no other stations on my frequency) until I deleted the _TWR position completely from TrackAudio (even with everything deselected!). 
Additional information: On this airport (EDDC), when adding _GND stations, the database gives you the _TWR station as an option too.
Unfortuanetly, I don't have a log file anymore.

**Comment by pierr3** [comment]
Can you please provide more details ? Did you use XC at all? The whole time, did you have your frequency on TX? You said the controller could hear you, could pilots too?

For the multiple stations added, that's normal, that's how your division setup AFV VCCS.

**Comment by Querbahn** [comment]
> Did you use XC at all? 
Not so sure anymore if it was ticked on my frequency (most likely not), but definetly not on the frequency I listened to. 

> The whole time, did you have your frequency on TX? 
Yes.

> You said the controller could hear you, could pilots too?
No idea.

> For the multiple stations added, that's normal, that's how your division setup AFV VCCS.
Sure, just wanted to give that piece of information.

**Comment by pierr3** [comment]
Closing as this should be fixed, please comment again if not on the latest version!
