### ISSUE TITLE
Becomes inactive when windows toggled

### ISSUE THREAD

**Issue by KingSpidey101** [pierr3/TrackAudio#73]
For the recent beta 5, facing an issue where in the track audio window becomes inactive when toggled to some other window eg Euroscope. This happens even when display always on top setting is enabled in settings.
So have to click on the TrackAudio window everytime to make it active in order to transmit.

**Comment by neilenns** [comment]
A few questions:

1. What platform are you on? Windows? 
2. If you are on Windows are you running any application as administrator? 
3. Are you using a key or a joystick button for PTT?

**Comment by pierr3** [comment]
Do you still receive audio, or is it only the Ptt that does not work? There has been no change in the code related to the Ptt, I'd recommend a full uninstall and reinstall

**Comment by KingSpidey101** [comment]
I could receive the audio. Just when transmitting, I had to click on trackaudio window first else it won't transmit. 
I will try reinstalling it and test and update you.

**Comment by neilenns** [comment]
@KingSpidey101 why do you run everything as administrator? There is no need to run TrackAudio as admin.

**Comment by KingSpidey101** [comment]
Updated to beta 6 and working fine now.

**Comment by pierr3** [comment]
Thanks
