### ISSUE TITLE
Unable to Add Stations With A Dash At The End

### ISSUE THREAD

**Issue by sunriselabs-digital** [pierr3/TrackAudio#74]
This is likely only a problem for the one ARTCC (ZBW) that I control at. However, I able currently unable to use Track Audio because I can not load any of the stations. Several months ago our FE moved the name for all of our AFV transceiver sites to "3LD_POS-". This was done in an effort to fix the problem of AFV picking up the position was online but was not adding all of the transceivers for a given position. So we added the hyphen to the end of all of our frequencies to prevent this behavior. Starting with the most recent update I am unable to add the frequencies that contain a hyphen in them. The feature was working before the last update, and worked in VectorAudio. I assume the most recent change is a filter on the client side now, as AFV still works normally.

**Comment by pierr3** [comment]
Correct, there is a filter that enforces that, I'll add the new character. Note that this approach is again, very non-standard and I wouldn't recommend using stations named like that

**Comment by pierr3** [comment]
Release is being pushed and will be available in the next couple minutes
