### ISSUE TITLE
Window restore

### ISSUE THREAD

**Issue by sheza5** [pierr3/TrackAudio#75]
When we have Trackaudio in a minimode state it opens in the same state again. Great. 

But if we start a new session the only option is to restore the full screen to log in to new position otherwise one does not have the option to see the login button. Like AFV can we get an interim restore option?
![Screenshot 2024-05-30 223121](https://github.com/pierr3/TrackAudio/assets/85385173/60e06a69-3f91-4d8f-aa78-c67f565dcbc5)

**Comment by pierr3** [comment]
Hey, no this will not be added, mini mode is mini mode only, and will not have more UI options, except we will add a maximise button. You can use the shortcut Ctrl+M to toggle between mini and maxi

**Comment by sheza5** [comment]
OK no problem.

**Comment by sheza5** [comment]
CTLR+M only brings in mini-mode but CTRL+M does not go back to max mode.

**Comment by neilenns** [comment]
I noticed that too. I'll look at fixing it when I add the restore button to mini mode.

**Comment by pierr3** [comment]
Ok strange because it should, try clicking in the middle of the mini window
and then hit the shortcut.

**Comment by sheza5** [comment]
No joy.
