### ISSUE TITLE
Implement Voice Activation Detection (VAD) for Enhanced VATSIM Communication

### ISSUE THREAD

**Issue by np123-glitch** [pierr3/TrackAudio#83]
#### Overview
Voice Activation Detection (VAD) is a technology designed to detect speech in audio streams, enabling the microphone to activate automatically when speech is detected and mute when it is not. Implementing VAD in VATSIM could dramatically enhance the clarity and efficiency of communications between pilots and controllers, especially during high-traffic events.

#### Benefits of VAD for VATSIM
1. **Enhanced Communication Clarity**: Automatically mutes the microphone when not in use, significantly reducing background noise and preventing cluttered communications.
2. **Efficient Use of Bandwidth**: Reduces the data transmitted by only sending audio data when necessary, maintaining system performance during large-scale events.
3. **Increased Realism**: Mimics real-world aviation communication practices by ensuring that only necessary communications are transmitted.
4. **Improved Accessibility**: Facilitates hands-free operation, making the platform more accessible to users with physical limitations or those who multitask during flights.
5. **Prevention of Accidental Transmissions**: Reduces the likelihood of open mic accidents that can disrupt sessions with irrelevant background noise.
6. **Better Integration with Voice Command Systems**: Ensures that voice commands are only registered when deliberately issued, enhancing the use of advanced user setups.

#### Proposed Implementation Strategy
- **Selecting a VAD Library**: Utilize a proven library such as WebRTC's VAD component for robust and efficient voice detection.
- **Integration with Current Audio Systems**: Seamlessly integrate VAD within VATSIM's existing audio handling frameworks to ensure compatibility and maintainability.
- **User-Controlled Settings**: Allow users to enable/disable VAD and adjust sensitivity settings through the VATSIM client interface to accommodate different environments and preferences.
- **Testing and Feedback**: Implement a beta testing phase where users can opt-in to test the VAD feature and provide feedback for further refinement.

#### Rationale for Implementation
The integration of VAD aligns with VATSIM's commitment to providing a realistic and high-quality simulation experience. As VATSIM hosts events with large numbers of participants, managing audio quality and efficiency becomes crucial. VAD not only enhances audio communication by focusing on speech but also optimizes bandwidth usage, which is vital for maintaining performance during peak usage.

#### Potential Challenges
- **Performance Impact**: Ensuring that the VAD implementation does not adversely affect the performance of the VATSIM client, especially on lower-specification hardware.
- **Environmental Variability**: Tuning VAD to accurately detect speech across various noisy environments that users may be participating from.

I believe the introduction of VAD would be a significant step forward in improving the operational efficiency and user satisfaction on VATSIM. Looking forward to community feedback and further discussions on this proposal!

This took way too long to write....

**Comment by pierr3** [comment]
Hi,

Thanks, but unfortunately this will not be implemented. VHF ATC Comms are PTT IRL, and will also remain PTT. A frequency is supposed to be "clean" when not in use. The possibility of unintended noise creates distractions for pilots, and risks blocking the frequency.
