### ISSUE TITLE
Mini Mode cannot use in full-screeen mode

### ISSUE THREAD

**Issue by AaronZSAM101** [pierr3/TrackAudio#84]
As the title, when the TrackAudio is set in full-screen mode, and keep the window on thde front, minimize mode cannot be used.

**Comment by neilenns** [comment]
Confirmed, here's the repo steps:

1. Hit the Windows maximize button
2. Hit the TrackAudio mini-mode toggle button

Result: Nothing happens

We probably have to do the API call to exit full screen mode before doing the window resize. I can look at this later today, should be a quick fix.
