### ISSUE TITLE
Performance issue under macOS ARM

### ISSUE THREAD

**Issue by KingfuChan** [pierr3/TrackAudio#88]
I'm using MacBook Air M2 with macOS Sonoma 14.5, installed istat menus to monitor system performance.

I noticed the situation: When I start TrackAudio inside macOS directly, the core temperature goes up to 59°C quickly. But when I start TrackAudio in my Windows 11 on ARM (Parallels Desktop VM), the core temperature only goes to about 43°C.

P.S. I haven't tried to connect to AFV normally in Windows VM, but in macOS the core temperature goes to 70°C or higher, which often indicated intense work load.

**Comment by pierr3** [comment]
I noticed this too and trying to track it down, it seems to be coming from the electron side
