### ISSUE TITLE
[macOS] beta 7 crashes on exit/quit, apple silicone

### ISSUE THREAD

**Issue by zladatm** [pierr3/TrackAudio#89]
Every time I quit using CMD+Q or the file menu the application hangs on exit then crashes.

**Comment by KingfuChan** [comment]
Seems related to #81 .

If I quit using CMD+Q, or quit when still connected to AFV, the system prompts for app crash.

If I disconnects from AFV first, then click on the top-left red close button, the app exits normally without warning.

**Comment by KingfuChan** [comment]
Quitting the app after disconnecting from AFV now works fine and ws message is properly sent.

However if AFV is still connected, When I click on the red close button or use CMD+Q, and I select quit in the pop-up window, the app goes irresponsive and I have to force kill it. In this case the ws close is not received (#81).
