### ISSUE TITLE
Modification request: Position of LAST RX

### ISSUE THREAD

**Issue by bostjanlaba** [pierr3/TrackAudio#97]
Hi, 

when listening to more than 1 station in TrackAudio, inside the Last RX field you get callsigns listed and separated by commas. Even with three listening stations, this text gets out of the box and also you cannot distinguish which callsign goes to which station.

So I would suggest the last rx would be moved into station boxes under frequency for example. There is just enough room if station name and freq get positioned up a little bit. This way even in mini mode, you would see all stations with corresponding last rx.

Just a suggestion.

Many thanks for very active development.

**Comment by neilenns** [comment]
I played around with this a bit, seeing if there was a way to fit the last rx into the station boxes. It never really worked out, particularly when there's a lot of stations in the window.

So I stole a page from mini-mode and converted the last rx list from comma separated to a straight list with station names. Works much better!

![image](https://github.com/pierr3/TrackAudio/assets/9524118/5845b704-f50a-419b-a470-3314c99e4634)
